files/urls.py
from django.urls import path, include
from files.views import *
from django.views.generic import TemplateView
app_name = 'files'
urlpatterns = [
    path('documents/', model_form_upload, name='documents'),
    path('dashboard/', showDocuments, name="dashboard"),
    path('contact-us/' , contact , name="contact" ),
]

uosfiles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users import urls as users_urls
from files import urls as files_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/files/' , include("files.api.urls")),
    path('' , TemplateView.as_view(template_name="home.html") , name="home"),
    path('users/' , include((users_urls , "users") , namespace="users" )),
    path('files/',  include((files_urls , "files") , namespace="files" )),
  #  path('contact-us/' , TemplateView.as_view(template_name="contact-us.html") , name="about-me"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path , include , re_path

from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView,
)

app_name = 'users'
urlpatterns = [
    path('login/' , LoginView.as_view() , name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('dashboard/' , views.redirectToDashboard  , name="dashboard"),
    path("signup/" , views.signup, name='signup'),
    path('password_change/', PasswordChangeView.as_view( success_url='users/password_change/done/'), name="password_change"),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password_reset/', PasswordResetView.as_view(success_url='done/'), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view( success_url='/users/reset/done/'), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^user/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='user'),
]

frontend/templates/about-me.html
{% extends "base.html"%}
{% block content %}
<style>
  h1 { font-size: 50px; }
</style>

    <div class="container" >
        <h1>Under Construction!</h1>
        <div>
            <p>This Webpage is still under construction! </p>
            <p>&mdash; The Team</p>
        </div>
    </div>
{% endblock %}

frontend/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en-GB">

<head>

    <meta charset="utf-8">
    <meta name="description" content="UosFiles to collect all the important  files in one website" />
    <meta name="keywords" content="uos files" />
    <meta name="author" content="Houzayfa Rifai" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}Welcome To UosFiles{% endblock %}</title>


    <!--[if lt IE 9]>
		    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
			<script src="js/https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js.js"></script>
		<![endif]-->

    <link rel="icon" type="image/png" href="https://image.ibb.co/jCXLnz/o.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sansita">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/syntaxy.dark.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>

<body>
    {% include "header.html" %} {% block content %} {% endblock content %}

    <script src="{% static 'js/jquery-3.1.1.min.js' %}"> </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"> </script>
    <script src="{% static 'js/code.js' %}"> </script>
    <script src="{% static 'js/wow.min.js' %}"> </script>
    <script> new WOW().init(); </script>
</body>

</html>

frontend/templates/contact-us.html
{% extends "base.html" %}
{% load bootstrap4 %} {% load i18n %} {% bootstrap_css %} {% bootstrap_javascript jquery='full'
%} {% bootstrap_messages %} {% load widget_tweaks %}
{% block content %}
<div class="container ">
    <form method="post">
  {% csrf_token %}
    <h3 class="my-4">We are always open to your suggestions !</h3>
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
    <div class="form-actions">
        <button type="submit" class="btn btn-success">Submit</button>
    </div>
</form>
</div>

{% endblock content%}

frontend/templates/dashboard.html
{% extends "base.html" %} {% load bootstrap4 %} {% load i18n %} {% bootstrap_css %} {% bootstrap_javascript jquery='full'
%} {% bootstrap_messages %} {% block content %}

<div class="container">
  <div class="col-sm-10  col-sm-offset-8">
    <form method="POST" action=".">
      {% csrf_token %}
      <div class="row">

        <div class="col-sm-5 mt-4" style="width: 400px;">
          <p> Please select a course : </p>
          <select id="crs" class="custom-select custom-select-sm" name="course">
            <option selected>Open this select menu</option>
            {% for obj in crs_names %}
            <option value="{{ obj.courses }}" name="course">{{ obj.courses }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      {% buttons %}
      <button type="submit" class="btn btn-success col-sm-2 mt-3">Search</button>
      {% endbuttons %}
    </form>
  </div>
</div>
<!-- enf of container div-->

{% if documents %}

<div class="container">
  <div class="row">
    {% for file in files%} {% for document in documents %}
    <div class="col-sm-5 mt-4">
      <div class="card">
        <div class="card-header ">
          {{filename}}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{document.title}}</h5>
          <p class="card-text">{{document.description}}</p>
          <a id="aaa" href="https://s3-ap-southeast-1.amazonaws.com/uosfiles-bucket/media/{{document.document}}" class="btn btn-success"
            download>Download</a>
        </div>
      </div>
    </div>
    {% endfor %} {% endfor %}
  </div>
</div>

{% else %} {% if not_found %}
<div class="container">
  <div class="alert alert-danger alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong>Not Found!</strong> {{ not_found }}
  </div>
</div>
{% endif %}
<script>
  originalLink = document.getElementById("aaa").getAttribute("href");
  document.getElementById("aaa").onclick = function () {
    document.getElementById("abc").href = originalLink.replace("%20", "+")
    return false;
  };
</script> {%endif%} {% endblock %}

frontend/templates/documents.html
{% extends "base.html" %}{% load widget_tweaks %} {% load bootstrap4 %} {% load i18n %} {% bootstrap_css %} {% bootstrap_javascript jquery='full'%} {% bootstrap_messages %} {% block content %}


<div class="container my-4">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-sm-8 ">
        {% csrf_token %}
                <small>{% bootstrap_form form %}</small>
            </div>
        </div>
        {% buttons %}
        <button type="submit" class="btn btn-success">Submit</button>
        {% endbuttons %}
    </form>
</div>


{% endblock %}

frontend/templates/header.html
<nav class="navbar navbar-expand-sm navbar-dark bg-success box-shadow">
    <a class="navbar-brand" href="/">UOSFiles</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#houzayfa" aria-controls="houzayfa"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse " id="houzayfa">
        {% if not user.is_authenticated %}

       <ul class="navbar-nav ml-auto ">
            <li class="nav-item active"><a class="nav-link" href="/">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'files:dashboard' %}">Courses</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'files:documents' %}">Upload Files</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Log In</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'files:contact' %}">Contact Us </a></li>
        </ul>

          {% else %}

        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'files:dashboard' %}"><i class="fas fa-chalkboard-teacher fa-1x  fa-fw aria-hidden='true' "></i> Dashboard</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'files:documents' %}"><i class="fas fa-file fa-1x  fa-fw aria-hidden='true'"></i> Files</a></li>

            <div class="dropdown" >
                <li class="btn btn-success dropdown-toggle" data-toggle="dropdown"> <i class="fas fa-graduation-cap fa-1x  fa-fw aria-hidden='true'"></i>{{ user.username }} </li>
                <li class="nav-item dropdown-menu"> <a  class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            </div>
        </ul>
        {% endif %}
    </div>
</nav>

frontend/templates/home.html
{% extends "base.html" %}{%load static %} {% block content %}
<!-- there is nothing to disply for now-->
<section>
  <div class="header-picture">
    <div class="container">
      <div class="row">
        <div class=" col-xs-8 col-mid-12">
          <h1 class=" my-2 wow fadeInDownBig" data-wow-duration="2s">Have Access To All The Files!</h1>
          <h4 class="my-5 wow  bounceInLeft" data-wow-duration="2s">-We are aiming to provide our users with previous quizzes, midterms and final in the near future!</h4>
        </div>
      </div>
    </div>
  </div>
</section>



<section>
  <div class="container">
    <h1 style="text-align: center;">Our Goals !</h1>
    <div class="row">
      <div class=" float-left col-xs-12 col-md-6">
        <p style="font-size: 20px;padding-left: 20px;margin-top:110px;">We are tirelessly working to collect the vast majority of files in order to save it in one place. UosFiles has meant
          to help UOS students to get the best grades through providing them with previous quizzes, midterms and finals.
          We are seeking your help in order to take
          <kbd>UOSFILES</kbd> to the next level where we can all work hand-to-hand in order to achieve our goal!</p>
        <p class="team">&#8702; The Team.</p>
      </div>
      <div class=" float-right col-xs-12 col-md-6">
        <img style="margin-top:50px;" src="{% static 'img/4.jpg' %}" class="img-fluid" alt="Cinque Terre">
      </div>

    </div>
    <hr>
  </div>
</section>
<!-- Services -->
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Services</h2>
      </div>
    </div>
    <div class="row text-center my-4">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fas fa-circle fa-stack-2x text-success"></i>
          <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
        </span>
        <p class="text-muted my-4">We have designed our website to be responsive to different devices and windows or screen sizes. </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fas fa-circle fa-stack-2x text-success"></i>
          <i class="fas fa-heart fa-stack-1x fa-inverse"></i>
        </span>
        <p class="text-muted my-4">Our Lovely design will make it easy for the user to use our service and will entice the students to use our website. </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fas fa-circle fa-stack-2x text-success"></i>
          <i class="fas fa-user-shield fa-stack-1x fa-inverse"></i>
        </span>
        <p class="text-muted my-4 ">We are working hard to keep our users safe from downloading any harmful files.We will be tracking every suspicious
          files and delete them</p>
      </div>
    </div>
  </div>
</section>


<footer class="footer center">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-xs-12 copyright">
        <h6> We love working alongside ambitious brands and people. Contact us if you'd like us to build something great together.</h6>
      </div>
    </div>
  </div>
</footer>
{% endblock content %}

frontend/templates/info.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
{% block content %}
<div class="container">
        <a href="{% url 'users:logout' %}">Logout</a>
</div>
{% endblock %}